include config.win

OBJS= src\clocks.obj src\core_profiler.obj src\function_meter.obj src\stack.obj src\lua50_profiler.obj

profiler: $(OBJS)
	move *.obj src
	mkdir bin
	link /dll /def:src\luaprofiler.def /out:$(PROFILER_OUTPUT) $(OBJS) $(LUA_LIB)


clean:
	del $(PROFILER_OUTPUT)
	rmdir bin
	del src\*.obj
